name: Android Cross-Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      NDK_VERSION: r25c
      TARGET: aarch64-linux-android31
      PROJECT_DIR: Frozen-Main

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip
        unzip -q android-ndk-${{ env.NDK_VERSION }}-linux.zip
        echo "NDK_PATH=$PWD/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV

    - name: Setup PowerShell
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Build executable
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'

        function log {
            [CmdletBinding()]
            Param(
                [Parameter(Mandatory = $true, Position = 0)]
                [string]$LogMessage
            )
            Write-Output ("[{0}] {1}" -f (Get-Date), $LogMessage)
        }

        # 设置项目路径
        $projectDir = "$env:PROJECT_DIR"
        $srcPath = "$projectDir/Frozen/src/main.cpp"
        $altSrcPath = "$projectDir/main.cpp"

        # 检查源文件是否存在
        if (-not (Test-Path $srcPath)) {
            log "主源文件 $srcPath 不存在，尝试备用路径"
            $srcPath = $altSrcPath
        }
        
        if (-not (Test-Path $srcPath)) {
            throw "未找到源文件: $srcPath"
        }

        log "使用源文件: $srcPath"
        
        # 设置编译器路径
        $ndkPath = $env:NDK_PATH
        $clang = Join-Path $ndkPath "toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"
        
        # 验证编译器是否存在
        if (-not (Test-Path $clang)) {
            throw "Clang++ not found at $clang"
        }

        $sysroot = "--sysroot=$(Join-Path $ndkPath 'toolchains/llvm/prebuilt/linux-x86_64/sysroot')"
        $cppFlags = "--target=$env:TARGET -std=c++20 -static -s -Ofast -flto -funroll-loops -finline-functions -fomit-frame-pointer -Wall -Wextra -Wshadow -fno-exceptions -fno-rtti -DNDEBUG -fPIE"
        
        log "正在创建构建目录"
        New-Item -ItemType Directory -Path ./build -Force | Out-Null
        
        log "构建中..."
        & $clang $sysroot $cppFlags.Split(' ') -I"$projectDir" -I"$projectDir/Frozen/src" $srcPath -o build/Frozen

        if (-not $?) {
            log "构建失败"
            exit 1
        }

        log "Frozen编译成功"
        Get-ChildItem ./build/Frozen
        log "文件大小: $((Get-Item ./build/Frozen).Length/1KB) KB"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-binary
        path: ./build/Frozen
