name: Android Cross-Compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NDK_VERSION: r25c
  PROJECT_DIR: Frozen-Main

jobs:

  # JOB 1: Build all architectures in parallel
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: ARM64
            target: aarch64-linux-android31
            output_name: FrozenARM64
          - arch: ARM32
            target: armv7a-linux-android31
            output_name: FrozenARM32
          - arch: X86
            target: i686-linux-android31
            output_name: FrozenX86
          - arch: X86_64
            target: x86_64-linux-android31
            output_name: FrozenX86_64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache NDK
      id: cache-ndk
      uses: actions/cache@v4
      with:
        path: android-ndk-${{ env.NDK_VERSION }}
        key: ${{ runner.os }}-ndk-${{ env.NDK_VERSION }}

    - name: Set up NDK (if cache miss)
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: |
        echo "Cache not found, downloading NDK..."
        wget -q https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip
        unzip -q android-ndk-${{ env.NDK_VERSION }}-linux.zip
        
    - name: Set NDK Path Environment Variable
      run: echo "NDK_PATH=$PWD/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV

    - name: Setup PowerShell
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Build for ${{ matrix.arch }}
      shell: pwsh
      env:
        TARGET: ${{ matrix.target }}
        OUTPUT_NAME: ${{ matrix.output_name }}
      run: |
        $ErrorActionPreference = 'Stop'
        function log { Write-Output ("[{0}] {1}" -f (Get-Date), $args[0]) }

        $projectDir = "$env:PROJECT_DIR"
        $srcPath = "$projectDir/Frozen/src/main.cpp"
        $outputFile = "build/$env:OUTPUT_NAME"

        if (-not (Test-Path $srcPath)) { $srcPath = "$projectDir/main.cpp" }
        if (-not (Test-Path $srcPath)) { throw "Source file not found." }
        log "Using source file: $srcPath"
        
        $ndkPath = $env:NDK_PATH
        $clang = Join-Path $ndkPath "toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"
        if (-not (Test-Path $clang)) { throw "Clang++ not found at $clang" }

        $sysroot = "--sysroot=$(Join-Path $ndkPath 'toolchains/llvm/prebuilt/linux-x86_64/sysroot')"
        $cppFlags = "--target=$env:TARGET -std=c++20 -static -s -Ofast -flto -funroll-loops -finline-functions -fomit-frame-pointer -Wall -Wextra -Wshadow -fno-exceptions -fno-rtti -DNDEBUG -fPIE"
        
        New-Item -ItemType Directory -Path ./build -Force | Out-Null
        
        log "Compiling for $env:TARGET..."
        & $clang $sysroot $cppFlags.Split(' ') -I"$projectDir" -I"$projectDir/Frozen/src" $srcPath -o $outputFile

        if (-not $?) { throw "Build failed for $env:TARGET" }
        log "$env:OUTPUT_NAME compiled successfully! Size: $((Get-Item $outputFile).Length/1KB) KB"

    # Each parallel job uploads its own, uniquely named artifact
    - name: Upload ${{ matrix.output_name }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}
        path: ./build/${{ matrix.output_name }}

  # JOB 2: Package all binaries into a single artifact
  package:
    runs-on: ubuntu-latest
    # This 'needs' directive ensures this job only runs after all matrix jobs in 'build' are successful
    needs: build

    steps:
    - name: Create download directory
      run: mkdir ./binaries

    # Download all artifacts from this workflow run into the 'binaries' directory
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./binaries

    # Upload the entire 'binaries' directory, which now contains all executables, as a single artifact
    - name: Upload combined artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-binaries
        path: ./binaries/
